### PR TITLE
Fix incorrect form data after submitting an edit-form

### LINKED ISSUE #138: NoSuchPropertyException when saving a form the 2nd time
When saving an entity for the 2nd time, the save controller throws a NoSuchPropertyException giving the "data" property as the name. Upon some research, I found that this is caused by the save-data.js file passing the complete response into setData instead of the data property
https://github.com/akeneo-labs/CustomEntityBundle/blob/master/Resources/public/js/form/common/save-form.js#L51

Full error log
```
[2018-01-18 16:45:36] request.CRITICAL: Uncaught PHP Exception Symfony\Component\PropertyAccess\Exception\NoSuchPropertyException: "Could not determine access type for property "data" in class "XXXXX\Bundle\CustomBundle\Entity\XXXXX"." at /srv/pim/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php line 639 {"exception":"[object] (Symfony\\Component\\PropertyAccess\\Exception\\NoSuchPropertyException(code: 0): Could not determine access type for property \"data\" in class \"XXXX\\Bundle\\CustomBundle\\Entity\\XXXX\". at /srv/pim/vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:639)"} []

```

### PR DESCRIPTION
**Pull request by mmetayer**
Fixes #138 and updates the example bundle

### CODE REVIEW

File: Normalizer/CustomEntityNormalizer.php [hunk 1]
```diff
@@ -43,21 +43,16 @@ public function normalize($entity, $format = null, array $context = []): array
     {
         $normalizedEntity = $this->pimSerializer->normalize($entity, 'standard', $context);
 
-        $meta = [
-            // Seems the upstream pim introduced some versioning for the javascript assets.
-            // Not sure how to implement this correct and dont have the time to investigate this now.
```
Comment (mmetayer) [inline Normalizer/CustomEntityNormalizer.php]: Actually the `structure_version` key is related to the entity's version (and not to the js asset's one)
